# Generated by Django 4.1.7 on 2023-03-18 14:16

from django.db import migrations
import user_fundoo.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_fundoo', '0002_alter_user_managers_remove_user_full_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user_fundoo.models.UserManager()),
            ],
        ),
    ]
