# Generated by Django 4.1.7 on 2023-04-10 08:21

from django.db import migrations
import user_fundoo.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_fundoo', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user_fundoo.models.UserManager()),
            ],
        ),
    ]
